server:
  port: 8080
#<<< Resilency / Circuit Breaker
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000  # 연결 timeout
        readTimeout: 610      # 응답 대기 timeout
        retryer:
          period: 2000        # 재시도 주기 
          maxPeriod: 5000     # 최대 재시도 주기 
          maxAttempts: 2      # 최대 재시도 횟수 
hystrix:
  command:
    # 전역설정
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610 # 읽기 타임아웃 (밀리초 단위)
#>>> Resilency / Circuit Breaker

spring:
  application:
    name: diary
---

spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./diary/testdb  # 파일 기반 H2 데이터베이스 경로
    driver-class-name: org.h2.Driver
    username: sa  # 기본 사용자 이름
    password:     # 기본 비밀번호 (빈 값)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2에 맞는 Hibernate Dialect 설정 추가
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: diary
#<<< EDA / Topic Name
          destination: alpb
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: alpb
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

openai-key: 
api:
  url: 
    diary: localhost:8085 
    

server:
  port: 8085

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: diary
          destination: alpb
          contentType: application/json
        event-out:
          destination: alpb
          contentType: application/json

api:
  url: 
    diary: diary:8080 
    

